services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: